# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kerem's Techblog
email: blog@codecut.de
description: >- # this means to ignore newlines until "baseurl:"
  For feedback or questions feel contact me thru email.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.codecut.de" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: kseyhan

author: Kerem Seyhan

logo: /assets/img/logo.png

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

show_excerpts: true

permalink: ":year/:month/:day/:title"

header_pages:
  - categories.md
  - tags.md
  - privacy.md
  - imprint.md

social:
  name: Kerem Seyhan
  links:
    - https://www.linkedin.com/in/kerem-seyhan-1189852b
    - https://www.xing.com/profile/Kerem_Seyhan
    - https://github.com/kseyhan

webmaster_verifications:
  google: HTPrOcpgKlO3ejNQOKll24-n3yz7KpIwzleR6APi15w
  bing: 508D8341F6E0DBCFB3F9FD852D29D154
  alexa: 1234
  yandex: 1b47c3c82dd07c0a
  baidu: 1234

# tag_page_layout: tag_page
# tag_page_dir: tag
# blog:
#   tags:
#     url: /blog/tags/
#     title_prefix: "blog - tag: "
#     layout: tag.html
# - jekyll-sitemap
# collections:
#   category:
#     output: true
# defaults:
#   - scope:
#       path: ""
#       type: category
#     values:
#       layout: "category"
# authors:
# defaults:
#   -
#     scope:
#       path: ""
#       type: "post"
#       values:
#         layout: "post"
#         title: "My Title"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - backup/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
